apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: app-user
          image: app-user
          imagePullPolicy: Never
          ports:
            - containerPort: 80
