apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-user
  namespace: monorepo-nmspc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: app-user
          image: app-user
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apps-user-service
  namespace: monorepo-nmspc
spec:
  selector:
    app: user
  ports:
    - name: default
      protocol: TCP
      port: 8080
      targetPort: 80
