apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
        - name: app-home
          image: app-home
          imagePullPolicy: Never
          ports:
            - containerPort: 80
