apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-home
  namespace: monorepo-nmspc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
        - name: app-home
          image: app-home
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apps-home-service
  namespace: monorepo-nmspc
spec:
  selector:
    app: home
  ports:
    - name: default
      protocol: TCP
      port: 8080
      targetPort: 80
